// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvwZdeXlpcX8NhZO7U-fYfvfAIzz-j0ao',
    appId: '1:203009489918:web:e3449c84924afdc6a29eaf',
    messagingSenderId: '203009489918',
    projectId: 'project-management-app-338dc',
    authDomain: 'project-management-app-338dc.firebaseapp.com',
    storageBucket: 'project-management-app-338dc.firebasestorage.app',
    measurementId: 'G-DHER9JW7K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDCHRqdvL2Skkv5tIN52PC6_qLlv2R2rk',
    appId: '1:203009489918:android:e5a2d6e787bf5572a29eaf',
    messagingSenderId: '203009489918',
    projectId: 'project-management-app-338dc',
    storageBucket: 'project-management-app-338dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsFpphtfjRKDRno_J2T_RR9ODYKwHseow',
    appId: '1:203009489918:ios:0702f1655ea364eca29eaf',
    messagingSenderId: '203009489918',
    projectId: 'project-management-app-338dc',
    storageBucket: 'project-management-app-338dc.firebasestorage.app',
    iosBundleId: 'com.example.projectManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsFpphtfjRKDRno_J2T_RR9ODYKwHseow',
    appId: '1:203009489918:ios:0702f1655ea364eca29eaf',
    messagingSenderId: '203009489918',
    projectId: 'project-management-app-338dc',
    storageBucket: 'project-management-app-338dc.firebasestorage.app',
    iosBundleId: 'com.example.projectManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvwZdeXlpcX8NhZO7U-fYfvfAIzz-j0ao',
    appId: '1:203009489918:web:2d418e49e2223cbda29eaf',
    messagingSenderId: '203009489918',
    projectId: 'project-management-app-338dc',
    authDomain: 'project-management-app-338dc.firebaseapp.com',
    storageBucket: 'project-management-app-338dc.firebasestorage.app',
    measurementId: 'G-NLCVGWJSNB',
  );
}
